import { Article } from "~/components/Article/Article";

import styles from './styles.module.css';

export default function Home() {
  return (
    <main>
      <h1>
        Petri Hänninen
      </h1>

      <p className={styles.lede}>
        I write code, climb rocks, click heads and am curious about pretty much everything.
      </p>

      <Article title="Foobar" date={new Date()}>
        <h3>Bar Foo</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel aliquet turpis. Nulla non dui viverra, malesuada lectus et, viverra diam. Maecenas vitae odio quis justo finibus pretium viverra eget ligula. Nulla et fringilla mi. In hac habitasse platea dictumst. Donec placerat malesuada quam, at tincidunt leo faucibus ut. Integer interdum nisl ac posuere dignissim. Curabitur ac eleifend lorem, sit amet pharetra neque. Phasellus fermentum vulputate nulla. Proin enim lorem, varius tempor porta a, dapibus eu justo. Curabitur ultricies faucibus tortor in dapibus. Suspendisse dolor tortor, pulvinar a condimentum in, vehicula eget mi. Integer vulputate suscipit neque, ac elementum est molestie sed. Nam tempor ac urna in sagittis. Sed pretium ligula non arcu tincidunt, ac venenatis ex pulvinar. Morbi bibendum massa eget purus rutrum porttitor.</p>
        <p>Curabitur congue enim id consectetur semper. Quisque consectetur metus lectus, nec aliquam odio faucibus at. Sed sagittis, odio ut congue aliquam, turpis sapien tristique erat, vitae egestas leo urna sed enim. Praesent facilisis aliquet diam, sed tempor neque dictum sit amet. Duis a euismod nisi. Sed eget neque lobortis, mollis augue a, porta quam. Nullam varius nisl eu felis molestie tincidunt. Etiam sed efficitur velit.</p>
        <p>Nulla vestibulum auctor nunc, in consequat dui auctor eu. Nam ut tellus dictum, egestas purus nec, sagittis ipsum. Maecenas a pellentesque nisl, eget tincidunt orci. Quisque fermentum aliquam ipsum, id fringilla dui bibendum non. Nunc sit amet bibendum ante. Phasellus malesuada elit ac neque interdum, in semper nunc egestas. Quisque venenatis quam urna, ac venenatis lorem tempus quis. Phasellus auctor maximus eros, ac consequat magna tempus luctus. Mauris a ligula quis nisi scelerisque varius.</p>
        <p>Maecenas quis rutrum mi, rutrum pretium nisi. Vivamus porta sodales bibendum. Phasellus tempus, nisl at laoreet pulvinar, tortor magna malesuada nisl, nec pellentesque orci lectus sit amet nisl. Integer ornare, orci in congue bibendum, dolor tortor imperdiet justo, vitae rhoncus ex magna vel erat. Nulla facilisi. Etiam felis mauris, maximus in nisl sed, ullamcorper congue purus. Donec lobortis sit amet urna nec blandit. Integer quam mi, luctus vitae aliquet nec, placerat ac ligula. Etiam ante ligula, egestas id augue sed, porta congue sem. Ut sit amet ornare neque. Sed ac lobortis enim. Cras congue purus eget mollis hendrerit. Aliquam vel mauris id tellus placerat tempor.</p>
        <h3>Bar Foo</h3>
        <p>Suspendisse quis massa vel enim sodales iaculis. Ut et nunc a ex gravida volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In lobortis sollicitudin gravida. Nam a dictum mauris. Sed dapibus mollis ex, non dapibus metus porta at. Ut ullamcorper, risus eget efficitur rutrum, arcu urna interdum mauris, quis pellentesque ante nisi a lacus. Vivamus a ante viverra, molestie sem id, consequat ipsum. Aliquam placerat et elit at pharetra. In vitae ante nec ligula scelerisque gravida. Nulla vel tristique nunc. Pellentesque ac lorem et lacus congue dapibus at vitae libero. Phasellus ut diam lacus. </p>
      </Article>

      <Article title="Foobar" date={new Date('2025-03-14')}>
        <h3>Bar Foo</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel aliquet turpis. Nulla non dui viverra, malesuada lectus et, viverra diam. Maecenas vitae odio quis justo finibus pretium viverra eget ligula. Nulla et fringilla mi. In hac habitasse platea dictumst. Donec placerat malesuada quam, at tincidunt leo faucibus ut. Integer interdum nisl ac posuere dignissim. Curabitur ac eleifend lorem, sit amet pharetra neque. Phasellus fermentum vulputate nulla. Proin enim lorem, varius tempor porta a, dapibus eu justo. Curabitur ultricies faucibus tortor in dapibus. Suspendisse dolor tortor, pulvinar a condimentum in, vehicula eget mi. Integer vulputate suscipit neque, ac elementum est molestie sed. Nam tempor ac urna in sagittis. Sed pretium ligula non arcu tincidunt, ac venenatis ex pulvinar. Morbi bibendum massa eget purus rutrum porttitor.</p>
        <p>Curabitur congue enim id consectetur semper. Quisque consectetur metus lectus, nec aliquam odio faucibus at. Sed sagittis, odio ut congue aliquam, turpis sapien tristique erat, vitae egestas leo urna sed enim. Praesent facilisis aliquet diam, sed tempor neque dictum sit amet. Duis a euismod nisi. Sed eget neque lobortis, mollis augue a, porta quam. Nullam varius nisl eu felis molestie tincidunt. Etiam sed efficitur velit.</p>
        <p>Nulla vestibulum auctor nunc, in consequat dui auctor eu. Nam ut tellus dictum, egestas purus nec, sagittis ipsum. Maecenas a pellentesque nisl, eget tincidunt orci. Quisque fermentum aliquam ipsum, id fringilla dui bibendum non. Nunc sit amet bibendum ante. Phasellus malesuada elit ac neque interdum, in semper nunc egestas. Quisque venenatis quam urna, ac venenatis lorem tempus quis. Phasellus auctor maximus eros, ac consequat magna tempus luctus. Mauris a ligula quis nisi scelerisque varius.</p>
        <p>Maecenas quis rutrum mi, rutrum pretium nisi. Vivamus porta sodales bibendum. Phasellus tempus, nisl at laoreet pulvinar, tortor magna malesuada nisl, nec pellentesque orci lectus sit amet nisl. Integer ornare, orci in congue bibendum, dolor tortor imperdiet justo, vitae rhoncus ex magna vel erat. Nulla facilisi. Etiam felis mauris, maximus in nisl sed, ullamcorper congue purus. Donec lobortis sit amet urna nec blandit. Integer quam mi, luctus vitae aliquet nec, placerat ac ligula. Etiam ante ligula, egestas id augue sed, porta congue sem. Ut sit amet ornare neque. Sed ac lobortis enim. Cras congue purus eget mollis hendrerit. Aliquam vel mauris id tellus placerat tempor.</p>
        <h3>Bar Foo</h3>
        <p>Suspendisse quis massa vel enim sodales iaculis. Ut et nunc a ex gravida volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In lobortis sollicitudin gravida. Nam a dictum mauris. Sed dapibus mollis ex, non dapibus metus porta at. Ut ullamcorper, risus eget efficitur rutrum, arcu urna interdum mauris, quis pellentesque ante nisi a lacus. Vivamus a ante viverra, molestie sem id, consequat ipsum. Aliquam placerat et elit at pharetra. In vitae ante nec ligula scelerisque gravida. Nulla vel tristique nunc. Pellentesque ac lorem et lacus congue dapibus at vitae libero. Phasellus ut diam lacus. </p>
      </Article>

      <Article title="Foobar" date={new Date('2025-01-01')}>
        <h3>Bar Foo</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel aliquet turpis. Nulla non dui viverra, malesuada lectus et, viverra diam. Maecenas vitae odio quis justo finibus pretium viverra eget ligula. Nulla et fringilla mi. In hac habitasse platea dictumst. Donec placerat malesuada quam, at tincidunt leo faucibus ut. Integer interdum nisl ac posuere dignissim. Curabitur ac eleifend lorem, sit amet pharetra neque. Phasellus fermentum vulputate nulla. Proin enim lorem, varius tempor porta a, dapibus eu justo. Curabitur ultricies faucibus tortor in dapibus. Suspendisse dolor tortor, pulvinar a condimentum in, vehicula eget mi. Integer vulputate suscipit neque, ac elementum est molestie sed. Nam tempor ac urna in sagittis. Sed pretium ligula non arcu tincidunt, ac venenatis ex pulvinar. Morbi bibendum massa eget purus rutrum porttitor.</p>
        <p>Curabitur congue enim id consectetur semper. Quisque consectetur metus lectus, nec aliquam odio faucibus at. Sed sagittis, odio ut congue aliquam, turpis sapien tristique erat, vitae egestas leo urna sed enim. Praesent facilisis aliquet diam, sed tempor neque dictum sit amet. Duis a euismod nisi. Sed eget neque lobortis, mollis augue a, porta quam. Nullam varius nisl eu felis molestie tincidunt. Etiam sed efficitur velit.</p>
        <p>Nulla vestibulum auctor nunc, in consequat dui auctor eu. Nam ut tellus dictum, egestas purus nec, sagittis ipsum. Maecenas a pellentesque nisl, eget tincidunt orci. Quisque fermentum aliquam ipsum, id fringilla dui bibendum non. Nunc sit amet bibendum ante. Phasellus malesuada elit ac neque interdum, in semper nunc egestas. Quisque venenatis quam urna, ac venenatis lorem tempus quis. Phasellus auctor maximus eros, ac consequat magna tempus luctus. Mauris a ligula quis nisi scelerisque varius.</p>
        <h3>Bar Foo</h3>
        <p>Maecenas quis rutrum mi, rutrum pretium nisi. Vivamus porta sodales bibendum. Phasellus tempus, nisl at laoreet pulvinar, tortor magna malesuada nisl, nec pellentesque orci lectus sit amet nisl. Integer ornare, orci in congue bibendum, dolor tortor imperdiet justo, vitae rhoncus ex magna vel erat. Nulla facilisi. Etiam felis mauris, maximus in nisl sed, ullamcorper congue purus. Donec lobortis sit amet urna nec blandit. Integer quam mi, luctus vitae aliquet nec, placerat ac ligula. Etiam ante ligula, egestas id augue sed, porta congue sem. Ut sit amet ornare neque. Sed ac lobortis enim. Cras congue purus eget mollis hendrerit. Aliquam vel mauris id tellus placerat tempor.</p>
        <p>Suspendisse quis massa vel enim sodales iaculis. Ut et nunc a ex gravida volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In lobortis sollicitudin gravida. Nam a dictum mauris. Sed dapibus mollis ex, non dapibus metus porta at. Ut ullamcorper, risus eget efficitur rutrum, arcu urna interdum mauris, quis pellentesque ante nisi a lacus. Vivamus a ante viverra, molestie sem id, consequat ipsum. Aliquam placerat et elit at pharetra. In vitae ante nec ligula scelerisque gravida. Nulla vel tristique nunc. Pellentesque ac lorem et lacus congue dapibus at vitae libero. Phasellus ut diam lacus. </p>
      </Article>
    </main>
  );
}
